### ISSUE TITLE
Delete all of a user's wishlists

### ISSUE THREAD

**Issue by minhlai** [NYU-Wishlists/wishlists#37] opened 2018-10-17 02:24 UTC
**As a** ... Customer
**I need** ... delete all my wishlists
**So that** ... my wife does not see my holiday shopping.

**Assumptions:**
* ... username is given

**Acceptance Criteria:**
```
Given ... A list of wishlists
When ... a customer requests to delete all their wishlists,
Then ... only their wishlists will be deleted.
```

**Comment by JiayuanHu** [comment] 2018-10-17 03:00
Duplicate of issue #38

**Closed** 2018-10-17 03:00 UTC
Labels: enhancement

**Comment by minhlai** [comment] 2018-10-17 03:42
closed as duplicate
